//-------------------
//----- examples below

import { catch_error_trace_output } from '../../domain/error-handle';

import { inspector } from '../error-handle';

function _link(text, title, href) {    
    const config = {      
      name: 'link',  
    };
}


const WR3_getWrapper = (name) => {
  return { literal: mainObj[name]['literal'] }
}

class CallbackFactory {

    error = false;



    create = (settings) => {
        

      // if(inspector(settings) throw new Error('nooooo settings')

        // if (!settings)
        // add error checking here.. probably few versions to test
        // error = false;



        // const { 
        //   config, name, 
        //   ooobj, replacerMethod, debug 
        // } = settings || false;

        // const { regex, replacer, literal } = ooobj;




        // config.name 

        // params: {
        //   content: title.trim(),
        //   href: href.trim(),
        // };

        
        // let partial;

        //here i want to apply a check and see if everything is fine, if not we generate error = true 
        // try {

        //     const replaced = replacerMethod(config);


        //     let newString = WR3_generateNewString(configCopy);
  
        //     return newString;
          
        //     return replaced;
        
        //   } catch (error) { catch_error_trace_output(error); }

         
          
          // partial = '';
      
          // isError = () => {
          //     return this.error;
          // }
          // setPartial = (string) => {
          //   this.partial = string;
          // }
      
          // getPartial = () => {
          //   return this.partial;
          // }
      
          // display = () => {
          //   this.getPartial();
          // }
    }


    
}

export default CallbackFactory;
